### ISSUE TITLE
Spells need to be added to Item

### ISSUE THREAD

**Issue by Psicoses** [Psicoses/RPG-Source#14]
Need to create a class that extends item for spells. So they can be added into inventory.

**Comment by RechargeableAA** [comment]
i planned to rename spells, to spellbooks. wont we need to make a separate class for spells that extends items like before?

**Comment by Psicoses** [comment]
Yes

> i planned to rename spells, to spellbooks. wont we need to make a separate class for spells that extends items like before?

I added kinda how i think they would work already, but we could rename them to spellbooks and add their functionality

**Comment by Psicoses** [comment]
Feature idea changed, moved to new issue
